#  관리자로서 존재하겠다
sudo: required
# 사용할 언어
language: generic
# 런타임 환경
services:
  - docker
# 실행전 해야할 것들 써주기
before_install:
  - docker build -t linojy06/docker-react-app -f Dockerfile.dev
#  실행 키워드 -e CI=true가 없으면 travis에서 에러남
script:
  - docker run -e CI=true lionjy06/docker-react-app npm run test -- --coverage
# 실행마친후 키워드
after_success:
  - echo "done!"
  - ls -al

# 