# 다음 as의 역할은 다음 from이 나올떄까지 builder로서 존재한다고 알려준다
FROM node:alpine as builder
WORKDIR /practice_react
COPY package.json /practice_react/
RUN npm install
COPY ./ ./
RUN npm run build

FROM nginx
# --from=builder는 as builder로 빌드한 내용을 가져온다는 뜻이고 build되어있는 경로를 첫번쨰로 그다음 그 경로에 있는 파일을 카피할곳을 두번쨰로 둔다
COPY --from=builder /practice_react/build /usr/share/nginx/html